### ISSUE TITLE
Version 0.10.X installation error

### ISSUE THREAD

**Issue by lauracysnet** [intersystems/ipm#809]
I have tried to install 0.10.X version (latest, and I have tried with 0.10.0 too), and I get this error after compiling all files:

```
USER>s version="latest" s r=##class(%Net.HttpRequest).%New(),r.Server="pm.community.intersystems.com",r.SSLConfiguration="ISC.FeatureTracker.SSL.Config" d r.Get("/packages/zpm/"_version_"/installer"),$system.OBJ.LoadStream(r.HttpResponse.Data,"c")
....
Compilation finished successfully in 3.294s.

Load finished successfully.

Compiling routine : %ZLANGC00.mac
Compiling routine : %ZLANGF00.mac2025-04-29 10:34:43 3 Evaluate: ${REGISTRY} -> https://pm.community.intersystems.com
2025-04-29 10:34:43 3 Evaluate: ${TRACKINGID} -> UA-126752118-1
2025-04-29 10:34:43 3 Evaluate: ${MODDIR} -> /tmp/dirOsRUJP/

[USER|ZPM]      Initialize START
Compilation started on 04/29/2025 10:34:47
Compiling class IPM.Installer
Compiling routine IPM.Installer.1
Compilation finished successfully in 0.054s.

[USER|ZPM]      Initialize SUCCESS
[USER|ZPM]      Reload START (/tmp/dirOsRUJP/)
[USER|ZPM]      Reload SUCCESS
[ZPM]   Module object refreshed.
[USER|ZPM]      Validate START
[USER|ZPM]      Validate SUCCESS
[USER|ZPM]      Compile START
[USER|ZPM]      Compile SUCCESS
[USER|ZPM]      Activate START
[ZPM]   Activate FAILURE
ERROR! File not copied: -32025-04-29 10:34:59 0 IPM.Installer: ERROR #5001: File not copied: -3
2025-04-29 10:34:59 0 IPM.Installer: Installation failed at 2025-04-29 10:34:59
2025-04-29 10:34:59 0 %Installer: Elapsed time 24.978745s
Time spent 24.985555
ERROR #5001: File not copied: -3
Detected 1 errors during load.
```

I can access zpm, but it doesn't show version:

```
USER > zpm
=============================================================================
|| Welcome to the Package Manager Shell (ZPM). Version:                    ||
|| Enter q/quit to exit the shell. Enter ?/help to view available commands ||
|| No registry configured                                                  ||
|| System Mode: <unset>                                                    ||
|| Mirror Status: NOTINIT                                                  ||
=============================================================================
IRIS for UNIX (Ubuntu Server LTS for ARM64 Containers) 2024.3 (Build 217U) Thu Nov 14 2024 17:36:33 EST [Health:8.2.0]
zpm:USER>
```

I have tried to install 0.9.2 version and everything works, so it seems it's a problem with version 0.10.X

**Comment by isc-tleavitt** [comment]
This is coming from (in module.xml):
```
  <!-- Pure python implementation of rpds-py for offline installation or behind a firewall. 
    It will be overriden at import-time if user installs the real rpds-py package.
    This is because mgr/python appears before lib/python in sys.path -->
  <FileCopy Name="modules/python/rpds.py" Target="${libdir}python/rpds.py"/>
```

Which is hitting issues due to mount permissions. @lauracysnet can you provide a bit more insight into your container's volumes/permissions (docker run command / docker-compose snippet etc.)? Are you running the IPM installation from the Dockerfile or in a running container?

**Comment by lauracysnet** [comment]
I'm running installation on an existing container. I have the container configured with a bind volume to a folder in my filesystem, so I can access to everything in IRIS. This is my docker-compose.yml:

```
version: '3.6'
services:
  irishealth:
    init: true
    build:
      context: .
      dockerfile: irishealth/Dockerfile
    hostname: irishealth
    container_name: irishealth
    ports: 
      # - 1972:1972
      - 10001:10001
    command: 
      - --check-caps false
      - --password-file /irishealth-shared/pass.txt
      - --key /irishealth-shared/iris.key
    volumes: 
      - type: bind
        source: ./irishealth/shared
        target: /irishealth-shared
      - type: bind
        source: ./otracarpeta/shared
        target: /otro-shared
    environment:
      - ISC_DATA_DIRECTORY=/irishealth-shared/iris
      - TZ=Europe/Madrid
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 8gb

# web gateway container
  webgateway:
    init: true
    container_name: webgateway
    build:
      context: .
      dockerfile: webgateway/Dockerfile
    hostname: webgateway
    ports:
    - "8880:80"
    - "8443:443"
    environment:
    - ISC_DATA_DIRECTORY=/webgateway-shared/durable
    - ISC_CSP_CONF_FILE=/webgateway-shared/CSP.conf
    - ISC_CSP_INI_FILE=/webgateway-shared/CSP.ini
    volumes:
    - ./webgateway/shared:/webgateway-shared
    depends_on:
    - irishealth
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1gb
```

I have this container since last year, and everything works fine. I wanted to start with IPM but I got stucked with latest version :(
